//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTSIMPLEHUMANBEHAVIOURPREDICTORCORE_HH
#define _COMPONENTSIMPLEHUMANBEHAVIOURPREDICTORCORE_HH

#include "Transformation.h"
#include "DomainHumanTracking/CommHumanPositionPredictions.hh"
#include "DomainHumanTracking/CommHumanPositionsAndVelocities.hh"
#include "aceSmartSoft.hh"
#include <iostream>

#define MAX_BODIES 6

class ComponentSimpleHumanBehaviourPredictorCore
{
private:

public:
	DomainHumanTracking::CommHumanPositionPredictions humanPositionPredictions;
	DomainHumanTracking::CommHumanPositionsAndVelocities humanPositionsAndVelocities;
	RUR_RobotMaths::Transformation worldToOutputFrame;
	double duration;
	RUR_RobotMaths::Vector maxPosition[MAX_BODIES];
	RUR_RobotMaths::Vector minPosition[MAX_BODIES];

	SmartACE::SmartMutex simpleHumanBehaviourPredictorMutex;

	ComponentSimpleHumanBehaviourPredictorCore();
};
	
#endif
