//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTHUMANSKELETONTRACKER_HH
#define _COMPONENTHUMANSKELETONTRACKER_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "ComponentHumanSkeletonTrackerCore.hh"

#include "ComponentHumanSkeletonTrackerPortFactoryInterface.hh"
#include "ComponentHumanSkeletonTrackerExtension.hh"

// forward declarations
class ComponentHumanSkeletonTrackerPortFactoryInterface;
class ComponentHumanSkeletonTrackerExtension;

// includes for ComponentHumanSkeletonTrackerROSExtension

// includes for OpcUaBackendComponentGeneratorExtension

// includes for PlainOpcUaComponentHumanSkeletonTrackerExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <DomainHumanTracking/CommHumanPositionsAndVelocities.hh>
#include <DomainHumanTracking/CommHumanPositionsAndVelocitiesACE.hh>
#include <DomainHumanTracking/CommHumanPositionsAndVelocitiesRequest.hh>
#include <DomainHumanTracking/CommHumanPositionsAndVelocitiesRequestACE.hh>
#include <DomainVision/CommRGBDImage.hh>
#include <DomainVision/CommRGBDImageACE.hh>

// include tasks
#include "FilterAndTrack.hh"
// include UpcallManagers
#include "RGBDImagePushServiceInUpcallManager.hh"

// include input-handler(s)
// include request-handler(s)
#include "HumanSkeletonsRequestAnswHandler.hh"

// include handler
#include "CompHandler.hh"

#include "ParameterStateStruct.hh"
#include "ParameterUpdateHandler.hh"

#include "SmartStateChangeHandler.hh"

#define COMP ComponentHumanSkeletonTracker::instance()

class ComponentHumanSkeletonTracker : public ComponentHumanSkeletonTrackerCore {
private:
	static ComponentHumanSkeletonTracker *_componentHumanSkeletonTracker;
	
	// constructor
	ComponentHumanSkeletonTracker();
	
	// copy-constructor
	ComponentHumanSkeletonTracker(const ComponentHumanSkeletonTracker& cc);
	
	// destructor
	~ComponentHumanSkeletonTracker() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, ComponentHumanSkeletonTrackerPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, ComponentHumanSkeletonTrackerExtension*> componentExtensionRegistry;
	
public:
	ParameterStateStruct getGlobalState() const
	{
		return paramHandler.getGlobalState();
	}
	
	ParameterStateStruct getParameters() const
	{
		return paramHandler.getGlobalState();
	}
	
	// define tasks
	Smart::TaskTriggerSubject* filterAndTrackTrigger;
	FilterAndTrack *filterAndTrack;
	
	// define input-ports
	// InputPort RGBDImagePushServiceIn
	Smart::IPushClientPattern<DomainVision::CommRGBDImage> *rGBDImagePushServiceIn;
	Smart::InputTaskTrigger<DomainVision::CommRGBDImage> *rGBDImagePushServiceInInputTaskTrigger;
	RGBDImagePushServiceInUpcallManager *rGBDImagePushServiceInUpcallManager;
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	Smart::IPushServerPattern<DomainHumanTracking::CommHumanPositionsAndVelocities> *humanSkeletonsPushServiceOut;
	
	// define answer-ports
	Smart::IQueryServerPattern<DomainHumanTracking::CommHumanPositionsAndVelocitiesRequest, DomainHumanTracking::CommHumanPositionsAndVelocities> *humanSkeletonsRequestAnsw;
	Smart::QueryServerTaskTrigger<DomainHumanTracking::CommHumanPositionsAndVelocitiesRequest, DomainHumanTracking::CommHumanPositionsAndVelocities> *humanSkeletonsRequestAnswInputTaskTrigger;
	
	// define request-handlers
	HumanSkeletonsRequestAnswHandler *humanSkeletonsRequestAnswHandler;
	
	// definitions of ComponentHumanSkeletonTrackerROSExtension
	
	// definitions of OpcUaBackendComponentGeneratorExtension
	
	// definitions of PlainOpcUaComponentHumanSkeletonTrackerExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	ParamUpdateHandler paramHandler;
	SmartACE::ParameterSlave *param;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, ComponentHumanSkeletonTrackerPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(ComponentHumanSkeletonTrackerExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	
	Smart::StatusCode connectRGBDImagePushServiceIn(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static ComponentHumanSkeletonTracker* instance()
	{
		if(_componentHumanSkeletonTracker == 0) {
			_componentHumanSkeletonTracker = new ComponentHumanSkeletonTracker();
		}
		return _componentHumanSkeletonTracker;
	}
	
	static void deleteInstance() {
		if(_componentHumanSkeletonTracker != 0) {
			delete _componentHumanSkeletonTracker;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct FilterAndTrack_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} filterAndTrack;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct HumanSkeletonsPushServiceOut_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} humanSkeletonsPushServiceOut;
		struct HumanSkeletonsRequestAnsw_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} humanSkeletonsRequestAnsw;
	
		//--- client port parameter ---
		struct RGBDImagePushServiceIn_struct {
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} rGBDImagePushServiceIn;
		
		// -- parameters for ComponentHumanSkeletonTrackerROSExtension
		
		// -- parameters for OpcUaBackendComponentGeneratorExtension
		
		// -- parameters for PlainOpcUaComponentHumanSkeletonTrackerExtension
		
	} connections;
};
#endif
