//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "HumanSkeletonsRequestAnswHandlerCore.hh"
#include "HumanSkeletonsRequestAnswHandler.hh"

// include observers

HumanSkeletonsRequestAnswHandlerCore::HumanSkeletonsRequestAnswHandlerCore(IQueryServer* server)
:	Smart::IInputHandler<std::pair<Smart::QueryIdPtr,DomainHumanTracking::CommHumanPositionsAndVelocitiesRequest>>(server)
,	server(server)
{
	
}

void HumanSkeletonsRequestAnswHandlerCore::updateAllCommObjects()
{
}

void HumanSkeletonsRequestAnswHandlerCore::notify_all_interaction_observers() {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	// try dynamically down-casting this class to the derived class 
	// (we can do it safely here as we exactly know the derived class)
	if(const HumanSkeletonsRequestAnswHandler* humanSkeletonsRequestAnswHandler = dynamic_cast<const HumanSkeletonsRequestAnswHandler*>(this)) {
		for(auto it=interaction_observers.begin(); it!=interaction_observers.end(); it++) {
			(*it)->on_update_from(humanSkeletonsRequestAnswHandler);
		}
	}
}

void HumanSkeletonsRequestAnswHandlerCore::attach_interaction_observer(HumanSkeletonsRequestAnswHandlerObserverInterface *observer) {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	interaction_observers.push_back(observer);
}

void HumanSkeletonsRequestAnswHandlerCore::detach_interaction_observer(HumanSkeletonsRequestAnswHandlerObserverInterface *observer) {
	std::unique_lock<std::mutex> lock(interaction_observers_mutex);
	interaction_observers.remove(observer);
}
