//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentHumanBehaviourPredictorOpcUaBackendPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "DomainHumanTrackingOpcUa/CommHumanPositionPredictionsOpcUa.hh"
#include "DomainHumanTrackingOpcUa/CommHumanPositionPredictionsRequestOpcUa.hh"
#include "DomainHumanTrackingOpcUa/CommHumanPositionsAndVelocitiesOpcUa.hh"

// create a static instance of the OpcUaBackendPortFactory
static ComponentHumanBehaviourPredictorOpcUaBackendPortFactory OpcUaBackendPortFactory;

ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::ComponentHumanBehaviourPredictorOpcUaBackendPortFactory()
{  
	componentImpl = 0;
	ComponentHumanBehaviourPredictor::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::~ComponentHumanBehaviourPredictorOpcUaBackendPortFactory()
{  }

void ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::initialize(ComponentHumanBehaviourPredictor *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}

Smart::IPushClientPattern<DomainHumanTracking::CommHumanPositionsAndVelocities> * ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::createHumanSkeletonsPushServiceIn()
{
	return new SeRoNet::OPCUA::Client::PushClient<DomainHumanTracking::CommHumanPositionsAndVelocities>(componentImpl);
}


Smart::IPushServerPattern<DomainHumanTracking::CommHumanPositionPredictions> * ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::createHumanPredictionsPushServiceOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<DomainHumanTracking::CommHumanPositionPredictions>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<DomainHumanTracking::CommHumanPositionPredictionsRequest, DomainHumanTracking::CommHumanPositionPredictions> * ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::createHumanPredictionsRequestAnsw(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::QueryServer<DomainHumanTracking::CommHumanPositionPredictionsRequest, DomainHumanTracking::CommHumanPositionPredictions>(componentImpl, serviceName);
}


int ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void ComponentHumanBehaviourPredictorOpcUaBackendPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
