//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMM3DVECTOR_H_
#define DOMAINHUMANTRACKING_COMM3DVECTOR_H_

#include "DomainHumanTracking/Comm3dVectorCore.hh"

namespace DomainHumanTracking {
		
class Comm3dVector : public Comm3dVectorCore {
	public:
		// default constructors
		Comm3dVector();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// Comm3dVector(const double &x = 0.0, const double &y = 0.0, const double &z = 0.0);
		
		Comm3dVector(const Comm3dVectorCore &comm3dVector);
		Comm3dVector(const DATATYPE &comm3dVector);
		virtual ~Comm3dVector();
		
		// use framework specific getter and setter methods from core (base) class
		using Comm3dVectorCore::get;
		using Comm3dVectorCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const Comm3dVector &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMM3DVECTOR_H_ */
