//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMBODYDATA_H_
#define DOMAINHUMANTRACKING_COMMBODYDATA_H_

#include "DomainHumanTracking/CommBodyDataCore.hh"

namespace DomainHumanTracking {
		
class CommBodyData : public CommBodyDataCore {
	public:
		// default constructors
		CommBodyData();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommBodyData(const CommBasicObjects::CommTimeStamp &acquisitionTime, const std::vector<DomainHumanTracking::CommJointData> &jointData, const bool &isTracked = false, const DomainHumanTracking::HandTrackingStateType &leftHandState = DomainHumanTracking::HandTrackingStateType(), const DomainHumanTracking::HandTrackingStateType &rightHandState = DomainHumanTracking::HandTrackingStateType());
		
		CommBodyData(const CommBodyDataCore &commBodyData);
		CommBodyData(const DATATYPE &commBodyData);
		virtual ~CommBodyData();
		
		// use framework specific getter and setter methods from core (base) class
		using CommBodyDataCore::get;
		using CommBodyDataCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommBodyData &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMMBODYDATA_H_ */
