//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENTHUMANBEHAVIOURPREDICTOR_ACE_PORTFACTORY_HH_
#define COMPONENTHUMANBEHAVIOURPREDICTOR_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "ComponentHumanBehaviourPredictorImpl.hh"

// include the main component-definition class
#include "ComponentHumanBehaviourPredictorPortFactoryInterface.hh"

class ComponentHumanBehaviourPredictorAcePortFactory: public ComponentHumanBehaviourPredictorPortFactoryInterface
{
private:
	ComponentHumanBehaviourPredictorImpl *componentImpl;
public:
	ComponentHumanBehaviourPredictorAcePortFactory();
	virtual ~ComponentHumanBehaviourPredictorAcePortFactory();

	virtual void initialize(ComponentHumanBehaviourPredictor *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<DomainHumanTracking::CommHumanPositionsAndVelocities> * createHumanSkeletonsPushServiceIn() override;
	
	virtual Smart::IPushServerPattern<DomainHumanTracking::CommHumanPositionPredictions> * createHumanPredictionsPushServiceOut(const std::string &serviceName) override;
	virtual Smart::IQueryServerPattern<DomainHumanTracking::CommHumanPositionPredictionsRequest, DomainHumanTracking::CommHumanPositionPredictions> * createHumanPredictionsRequestAnsw(const std::string &serviceName) override;
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* COMPONENTHUMANBEHAVIOURPREDICTOR_ACE_PORTFACTORY_HH_ */
