//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "HumanSkeletonsPushServiceInUpcallManager.hh"

HumanSkeletonsPushServiceInUpcallManager::HumanSkeletonsPushServiceInUpcallManager(
	Smart::InputSubject<DomainHumanTracking::CommHumanPositionsAndVelocities> *subject,
	const int &prescaleFactor)
	:	Smart::IInputHandler<DomainHumanTracking::CommHumanPositionsAndVelocities>(subject, prescaleFactor)
{  }
HumanSkeletonsPushServiceInUpcallManager::~HumanSkeletonsPushServiceInUpcallManager()
{  }

void HumanSkeletonsPushServiceInUpcallManager::notify_upcalls(const DomainHumanTracking::CommHumanPositionsAndVelocities &input)
{
	for(auto it=upcalls.begin(); it!=upcalls.end(); it++) {
		(*it)->on_HumanSkeletonsPushServiceIn(input);
	}
}

void HumanSkeletonsPushServiceInUpcallManager::attach(HumanSkeletonsPushServiceInUpcallInterface *upcall)
{
	upcalls.push_back(upcall);
}
void HumanSkeletonsPushServiceInUpcallManager::detach(HumanSkeletonsPushServiceInUpcallInterface *upcall)
{
	upcalls.remove(upcall);
}
