//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _HUMANSKELETONSPUSHSERVICEIN_UPCALL_MANAGER_HH
#define _HUMANSKELETONSPUSHSERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "HumanSkeletonsPushServiceInUpcallInterface.hh"

/** HumanSkeletonsPushServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort HumanSkeletonsPushServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class HumanSkeletonsPushServiceInUpcallManager
:	public Smart::IInputHandler<DomainHumanTracking::CommHumanPositionsAndVelocities>
{
private:
	// list of associated updalls
	std::list<HumanSkeletonsPushServiceInUpcallInterface*> upcalls;

	// call the on_HumanSkeletonsPushServiceIn of all the attached HumanSkeletonsPushServiceInUpcallInterfaces
	void notify_upcalls(const DomainHumanTracking::CommHumanPositionsAndVelocities &input);
	
protected:
	virtual void handle_input(const DomainHumanTracking::CommHumanPositionsAndVelocities &input) {
		// relay input-handling to all attached HumanSkeletonsPushServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	HumanSkeletonsPushServiceInUpcallManager(
		Smart::InputSubject<DomainHumanTracking::CommHumanPositionsAndVelocities> *subject,
		const int &prescaleFactor=1
	);
	virtual ~HumanSkeletonsPushServiceInUpcallManager();
	
	void attach(HumanSkeletonsPushServiceInUpcallInterface *upcall);
	void detach(HumanSkeletonsPushServiceInUpcallInterface *upcall);
};

#endif
