//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include <iostream>
#include "ComponentHumanBehaviourPredictorCore.hh"

// constructor
ComponentHumanBehaviourPredictorCore::ComponentHumanBehaviourPredictorCore():
duration(1.0)
{
	std::cout << "constructor ComponentHumanBehaviourPredictorCore\n";

	for (int bodyIndex = 0; bodyIndex < MAX_BODIES; bodyIndex++)
	{
		maxPosition[bodyIndex] = RUR_RobotMaths::Vector::MinusOnes(3) * DBL_MAX;
		minPosition[bodyIndex] = RUR_RobotMaths::Vector::Ones(3) * DBL_MAX;
	}
}
