//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIESREQUEST_CORE_H_
#define DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIESREQUEST_CORE_H_

#include "DomainHumanTracking/CommHumanPositionsAndVelocitiesRequestData.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainHumanTracking {
	
class CommHumanPositionsAndVelocitiesRequestCore {
protected:
	// data structure
	DomainHumanTrackingIDL::CommHumanPositionsAndVelocitiesRequest idl_CommHumanPositionsAndVelocitiesRequest;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainHumanTrackingIDL::CommHumanPositionsAndVelocitiesRequest DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommHumanPositionsAndVelocitiesRequestCore();
	CommHumanPositionsAndVelocitiesRequestCore(const DATATYPE &data);
	// default destructor
	virtual ~CommHumanPositionsAndVelocitiesRequestCore();
	
	const DATATYPE& get() const { return idl_CommHumanPositionsAndVelocitiesRequest; }
	operator const DATATYPE&() const { return idl_CommHumanPositionsAndVelocitiesRequest; }
	DATATYPE& set() { return idl_CommHumanPositionsAndVelocitiesRequest; }

	static inline std::string identifier(void) { return "DomainHumanTracking::CommHumanPositionsAndVelocitiesRequest"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Dummy
	inline bool getDummy() const { return idl_CommHumanPositionsAndVelocitiesRequest.dummy; }
	inline CommHumanPositionsAndVelocitiesRequestCore& setDummy(const bool &dummy) { idl_CommHumanPositionsAndVelocitiesRequest.dummy = dummy; return *this; }
};

} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIESREQUEST_CORE_H_ */
