//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/CommHumanPositionsAndVelocitiesACE.hh"
#include <ace/SString.h>
#include "DomainHumanTracking/CommBodyDataACE.hh"

// serialization operator for element CommHumanPositionsAndVelocities
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTrackingIDL::CommHumanPositionsAndVelocities &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element bodyData
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.bodyData.size());
	std::vector<DomainHumanTrackingIDL::CommBodyData>::const_iterator data_bodyDataIt;
	for(data_bodyDataIt=data.bodyData.begin(); data_bodyDataIt!=data.bodyData.end(); data_bodyDataIt++) {
		good_bit = good_bit && cdr << *data_bodyDataIt;
	}
	
	return good_bit;
}

// de-serialization operator for element CommHumanPositionsAndVelocities
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTrackingIDL::CommHumanPositionsAndVelocities &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize list-type element bodyData
	ACE_CDR::ULong data_bodyDataNbr;
	good_bit = good_bit && cdr >> data_bodyDataNbr;
	data.bodyData.clear();
	DomainHumanTrackingIDL::CommBodyData data_bodyDataItem;
	for(ACE_CDR::ULong i=0; i<data_bodyDataNbr; ++i) {
		good_bit = good_bit && cdr >> data_bodyDataItem;
		data.bodyData.push_back(data_bodyDataItem);
	}
	
	return good_bit;
}

// serialization operator for CommunicationObject CommHumanPositionsAndVelocities
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTracking::CommHumanPositionsAndVelocities &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommHumanPositionsAndVelocities
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTracking::CommHumanPositionsAndVelocities &obj)
{
	return cdr >> obj.set();
}
