//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIES_CORE_H_
#define DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIES_CORE_H_

#include "DomainHumanTracking/CommHumanPositionsAndVelocitiesData.hh"
#include "DomainHumanTracking/CommBodyData.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainHumanTracking {
	
class CommHumanPositionsAndVelocitiesCore {
protected:
	// data structure
	DomainHumanTrackingIDL::CommHumanPositionsAndVelocities idl_CommHumanPositionsAndVelocities;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainHumanTrackingIDL::CommHumanPositionsAndVelocities DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommHumanPositionsAndVelocitiesCore();
	CommHumanPositionsAndVelocitiesCore(const DATATYPE &data);
	// default destructor
	virtual ~CommHumanPositionsAndVelocitiesCore();
	
	const DATATYPE& get() const { return idl_CommHumanPositionsAndVelocities; }
	operator const DATATYPE&() const { return idl_CommHumanPositionsAndVelocities; }
	DATATYPE& set() { return idl_CommHumanPositionsAndVelocities; }

	static inline std::string identifier(void) { return "DomainHumanTracking::CommHumanPositionsAndVelocities"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element BodyData
	/**
	 * Getter methods for element idl_CommHumanPositionsAndVelocities.bodyData of type vector<DomainHumanTracking::CommBodyData>
	 */
	inline std::vector<DomainHumanTracking::CommBodyData> getBodyDataCopy() const { 
		return std::vector<DomainHumanTracking::CommBodyData>(idl_CommHumanPositionsAndVelocities.bodyData.begin(), idl_CommHumanPositionsAndVelocities.bodyData.end());
	}
	inline DomainHumanTracking::CommBodyData getBodyDataElemAtPos(const size_t &pos) const {
		return DomainHumanTracking::CommBodyData(idl_CommHumanPositionsAndVelocities.bodyData[pos]);
	}
	inline size_t getBodyDataSize() const { return idl_CommHumanPositionsAndVelocities.bodyData.size(); }
	inline bool isBodyDataEmpty() const { return idl_CommHumanPositionsAndVelocities.bodyData.empty(); }
	/**
	 * Setter methods for idl_CommHumanPositionsAndVelocities.bodyData of type vector<DomainHumanTracking::CommBodyData>
	 */
	inline CommHumanPositionsAndVelocitiesCore& setBodyData(const std::vector<DomainHumanTracking::CommBodyData> &bodyData) { 
		idl_CommHumanPositionsAndVelocities.bodyData.assign(bodyData.begin(), bodyData.end());
		return *this;
	}
	inline bool setBodyDataElemAtPos(const size_t &pos, const DomainHumanTracking::CommBodyData &elem) {
		if(pos < idl_CommHumanPositionsAndVelocities.bodyData.size()) {
			idl_CommHumanPositionsAndVelocities.bodyData[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertBodyDataVectorAtPos(const size_t &pos, const std::vector<DomainHumanTracking::CommBodyData> &data) {
		if(pos < idl_CommHumanPositionsAndVelocities.bodyData.size()) {
			idl_CommHumanPositionsAndVelocities.bodyData.insert(idl_CommHumanPositionsAndVelocities.bodyData.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeBodyData(const size_t &size) { idl_CommHumanPositionsAndVelocities.bodyData.resize(size); }
	inline bool eraseBodyDataElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommHumanPositionsAndVelocities.bodyData.size() ) {
			idl_CommHumanPositionsAndVelocities.bodyData.erase(idl_CommHumanPositionsAndVelocities.bodyData.begin()+pos, idl_CommHumanPositionsAndVelocities.bodyData.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearBodyData() { idl_CommHumanPositionsAndVelocities.bodyData.clear(); }
};

} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMMHUMANPOSITIONSANDVELOCITIES_CORE_H_ */
