//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/Comm3dVectorACE.hh"
#include <ace/SString.h>

// serialization operator for element Comm3dVector
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTrackingIDL::Comm3dVector &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element x
	good_bit = good_bit && cdr.write_double(data.x);
	// serialize list-element y
	good_bit = good_bit && cdr.write_double(data.y);
	// serialize list-element z
	good_bit = good_bit && cdr.write_double(data.z);
	
	return good_bit;
}

// de-serialization operator for element Comm3dVector
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTrackingIDL::Comm3dVector &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element x
	good_bit = good_bit && cdr.read_double(data.x);
	// deserialize type element y
	good_bit = good_bit && cdr.read_double(data.y);
	// deserialize type element z
	good_bit = good_bit && cdr.read_double(data.z);
	
	return good_bit;
}

// serialization operator for CommunicationObject Comm3dVector
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTracking::Comm3dVector &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject Comm3dVector
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTracking::Comm3dVector &obj)
{
	return cdr >> obj.set();
}
