//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/CommHumanPositionsAndVelocitiesCore.hh"

// serialization/deserialization operators
//#include "DomainHumanTracking/CommHumanPositionsAndVelocitiesACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainHumanTracking 
{
	const char* CommHumanPositionsAndVelocitiesCore::getCompiledHash()
	{
		return DomainHumanTrackingIDL::REPO_HASH;
	}
	
	void CommHumanPositionsAndVelocitiesCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for DomainHumanTracking::CommBodyData(idl_CommHumanPositionsAndVelocities.bodyData)
		DomainHumanTracking::CommBodyData::getAllHashValues(hashes);
	}
	
	void CommHumanPositionsAndVelocitiesCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommHumanPositionsAndVelocitiesCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for DomainHumanTracking::CommBodyData(idl_CommHumanPositionsAndVelocities.bodyData)
		DomainHumanTracking::CommBodyData::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommHumanPositionsAndVelocitiesCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<DomainHumanTrackingIDL::CommBodyData>::const_iterator data_bodyDataIt;
		for(data_bodyDataIt=data.bodyData.begin(); data_bodyDataIt!=data.bodyData.end(); data_bodyDataIt++) {
			seed += DomainHumanTracking::CommBodyData::generateDataHash(*data_bodyDataIt);
		}
		
		return seed;
	}
	#endif
	
	// default constructor
	CommHumanPositionsAndVelocitiesCore::CommHumanPositionsAndVelocitiesCore()
	:	idl_CommHumanPositionsAndVelocities()
	{  
		setBodyData(std::vector<DomainHumanTracking::CommBodyData>());
	}
	
	CommHumanPositionsAndVelocitiesCore::CommHumanPositionsAndVelocitiesCore(const DATATYPE &data)
	:	idl_CommHumanPositionsAndVelocities(data)
	{  }

	CommHumanPositionsAndVelocitiesCore::~CommHumanPositionsAndVelocitiesCore()
	{  }
	
	void CommHumanPositionsAndVelocitiesCore::to_ostream(std::ostream &os) const
	{
	  os << "CommHumanPositionsAndVelocities(";
	  std::vector<DomainHumanTracking::CommBodyData>::const_iterator bodyDataIt;
	  std::vector<DomainHumanTracking::CommBodyData> bodyDataList = getBodyDataCopy();
	  for(bodyDataIt=bodyDataList.begin(); bodyDataIt!=bodyDataList.end(); bodyDataIt++) {
	  	bodyDataIt->to_ostream(os);
	  }
	  os << ") ";
	}
	
	// convert to xml stream
	void CommHumanPositionsAndVelocitiesCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<DomainHumanTracking::CommBodyData>::const_iterator bodyDataIt;
		std::vector<DomainHumanTracking::CommBodyData> bodyDataList = getBodyDataCopy();
		counter = 0;
		os << indent << "<bodyDataList n=\"" << bodyDataList.size() << "\">";
		for(bodyDataIt=bodyDataList.begin(); bodyDataIt!=bodyDataList.end(); bodyDataIt++) {
			os << indent << "<bodyData i=\"" << counter++ << "\">";
			bodyDataIt->to_xml(os, indent);
			os << indent << "</bodyData>";
		}
		os << indent << "</bodyDataList>";
	}
	
	// restore from xml stream
	void CommHumanPositionsAndVelocitiesCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_bodyDataList("<bodyDataList n=\"");
		static const Smart::KnuthMorrisPratt kmp_bodyData("\">");
		
		if(kmp_bodyDataList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			DomainHumanTracking::CommBodyData bodyDataItem;
			std::vector<DomainHumanTracking::CommBodyData> bodyDataList;
			kmp_bodyData.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_bodyData.search(is)) {
					bodyDataItem.from_xml(is);
					bodyDataList.push_back(bodyDataItem);
				}
			}
			setBodyData(bodyDataList);
		}
	}
	
	/*
	void CommHumanPositionsAndVelocitiesCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainHumanTrackingIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainHumanTrackingIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommHumanPositionsAndVelocitiesACE.hh)
		cdr << idl_CommHumanPositionsAndVelocities;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommHumanPositionsAndVelocities);
		cdr << data_hash;
		// std::cout << "CommHumanPositionsAndVelocitiesCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommHumanPositionsAndVelocitiesCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainHumanTrackingIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommHumanPositionsAndVelocitiesACE.hh)
		cdr >> idl_CommHumanPositionsAndVelocities;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommHumanPositionsAndVelocities);
		assert(data_hash == own_hash);
		// std::cout << "CommHumanPositionsAndVelocitiesCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainHumanTracking */
