//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/CommJointDataCore.hh"

// serialization/deserialization operators
//#include "DomainHumanTracking/CommJointDataACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainHumanTracking 
{
	const char* CommJointDataCore::getCompiledHash()
	{
		return DomainHumanTrackingIDL::REPO_HASH;
	}
	
	void CommJointDataCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for DomainHumanTracking::Comm2dVector(idl_CommJointData.jointPosition2D)
		DomainHumanTracking::Comm2dVector::getAllHashValues(hashes);
		// get hash value(s) for DomainHumanTracking::Comm2dVector(idl_CommJointData.jointVelocity2D)
		DomainHumanTracking::Comm2dVector::getAllHashValues(hashes);
		// get hash value(s) for DomainHumanTracking::Comm3dVector(idl_CommJointData.jointPosition3d)
		DomainHumanTracking::Comm3dVector::getAllHashValues(hashes);
		// get hash value(s) for DomainHumanTracking::Comm3dVector(idl_CommJointData.jointVelocity3d)
		DomainHumanTracking::Comm3dVector::getAllHashValues(hashes);
	}
	
	void CommJointDataCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommJointDataCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for DomainHumanTracking::Comm2dVector(idl_CommJointData.jointPosition2D)
		DomainHumanTracking::Comm2dVector::checkAllHashValues(hashes);
		// check hash value(s) for DomainHumanTracking::Comm2dVector(idl_CommJointData.jointVelocity2D)
		DomainHumanTracking::Comm2dVector::checkAllHashValues(hashes);
		// check hash value(s) for DomainHumanTracking::Comm3dVector(idl_CommJointData.jointPosition3d)
		DomainHumanTracking::Comm3dVector::checkAllHashValues(hashes);
		// check hash value(s) for DomainHumanTracking::Comm3dVector(idl_CommJointData.jointVelocity3d)
		DomainHumanTracking::Comm3dVector::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommJointDataCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.isJointTracked);
		seed += DomainHumanTracking::Comm2dVector::generateDataHash(data.jointPosition2D);
		seed += DomainHumanTracking::Comm2dVector::generateDataHash(data.jointVelocity2D);
		seed += DomainHumanTracking::Comm3dVector::generateDataHash(data.jointPosition3d);
		seed += DomainHumanTracking::Comm3dVector::generateDataHash(data.jointVelocity3d);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommJointDataCore::CommJointDataCore()
	:	idl_CommJointData()
	{  
		setIsJointTracked(DomainHumanTracking::JointTrackingStateType());
		setJointPosition2D(DomainHumanTracking::Comm2dVector());
		setJointVelocity2D(DomainHumanTracking::Comm2dVector());
		setJointPosition3d(DomainHumanTracking::Comm3dVector());
		setJointVelocity3d(DomainHumanTracking::Comm3dVector());
	}
	
	CommJointDataCore::CommJointDataCore(const DATATYPE &data)
	:	idl_CommJointData(data)
	{  }

	CommJointDataCore::~CommJointDataCore()
	{  }
	
	void CommJointDataCore::to_ostream(std::ostream &os) const
	{
	  os << "CommJointData(";
	  getIsJointTracked().to_ostream(os);
	  getJointPosition2D().to_ostream(os);
	  getJointVelocity2D().to_ostream(os);
	  getJointPosition3d().to_ostream(os);
	  getJointVelocity3d().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void CommJointDataCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<isJointTracked>";
		getIsJointTracked().to_xml(os, indent);
		os << indent << "</isJointTracked>";
		os << indent << "<jointPosition2D>";
		getJointPosition2D().to_xml(os, indent);
		os << indent << "</jointPosition2D>";
		os << indent << "<jointVelocity2D>";
		getJointVelocity2D().to_xml(os, indent);
		os << indent << "</jointVelocity2D>";
		os << indent << "<jointPosition3d>";
		getJointPosition3d().to_xml(os, indent);
		os << indent << "</jointPosition3d>";
		os << indent << "<jointVelocity3d>";
		getJointVelocity3d().to_xml(os, indent);
		os << indent << "</jointVelocity3d>";
	}
	
	// restore from xml stream
	void CommJointDataCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_isJointTracked("<isJointTracked>");
		static const Smart::KnuthMorrisPratt kmp_jointPosition2D("<jointPosition2D>");
		static const Smart::KnuthMorrisPratt kmp_jointVelocity2D("<jointVelocity2D>");
		static const Smart::KnuthMorrisPratt kmp_jointPosition3d("<jointPosition3d>");
		static const Smart::KnuthMorrisPratt kmp_jointVelocity3d("<jointVelocity3d>");
		
		if(kmp_isJointTracked.search(is)) {
			DomainHumanTracking::JointTrackingStateType isJointTrackedItem;
			isJointTrackedItem.from_xml(is);
			setIsJointTracked(isJointTrackedItem);
		}
		if(kmp_jointPosition2D.search(is)) {
			DomainHumanTracking::Comm2dVector jointPosition2DItem;
			jointPosition2DItem.from_xml(is);
			setJointPosition2D(jointPosition2DItem);
		}
		if(kmp_jointVelocity2D.search(is)) {
			DomainHumanTracking::Comm2dVector jointVelocity2DItem;
			jointVelocity2DItem.from_xml(is);
			setJointVelocity2D(jointVelocity2DItem);
		}
		if(kmp_jointPosition3d.search(is)) {
			DomainHumanTracking::Comm3dVector jointPosition3dItem;
			jointPosition3dItem.from_xml(is);
			setJointPosition3d(jointPosition3dItem);
		}
		if(kmp_jointVelocity3d.search(is)) {
			DomainHumanTracking::Comm3dVector jointVelocity3dItem;
			jointVelocity3dItem.from_xml(is);
			setJointVelocity3d(jointVelocity3dItem);
		}
	}
	
	/*
	void CommJointDataCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainHumanTrackingIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainHumanTrackingIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommJointDataACE.hh)
		cdr << idl_CommJointData;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommJointData);
		cdr << data_hash;
		// std::cout << "CommJointDataCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommJointDataCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainHumanTrackingIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommJointDataACE.hh)
		cdr >> idl_CommJointData;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommJointData);
		assert(data_hash == own_hash);
		// std::cout << "CommJointDataCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainHumanTracking */
