//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/CommPredictedDataCore.hh"

// serialization/deserialization operators
//#include "DomainHumanTracking/CommPredictedDataACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainHumanTracking 
{
	const char* CommPredictedDataCore::getCompiledHash()
	{
		return DomainHumanTrackingIDL::REPO_HASH;
	}
	
	void CommPredictedDataCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommPredictedDataCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommPredictedDataCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommPredictedDataCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.valid);
		boost::hash_combine(seed, data.xMaxLimit);
		boost::hash_combine(seed, data.xMinLimit);
		boost::hash_combine(seed, data.yMaxLimit);
		boost::hash_combine(seed, data.yMinLimit);
		boost::hash_combine(seed, data.zMaxLimit);
		boost::hash_combine(seed, data.zMinLimit);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommPredictedDataCore::CommPredictedDataCore()
	:	idl_CommPredictedData()
	{  
		setValid(false);
		setXMaxLimit(0.0);
		setXMinLimit(0.0);
		setYMaxLimit(0.0);
		setYMinLimit(0.0);
		setZMaxLimit(0.0);
		setZMinLimit(0.0);
	}
	
	CommPredictedDataCore::CommPredictedDataCore(const DATATYPE &data)
	:	idl_CommPredictedData(data)
	{  }

	CommPredictedDataCore::~CommPredictedDataCore()
	{  }
	
	void CommPredictedDataCore::to_ostream(std::ostream &os) const
	{
	  os << "CommPredictedData(";
	  os << getValid() << " ";
	  os << getXMaxLimit() << " ";
	  os << getXMinLimit() << " ";
	  os << getYMaxLimit() << " ";
	  os << getYMinLimit() << " ";
	  os << getZMaxLimit() << " ";
	  os << getZMinLimit() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommPredictedDataCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<valid>" << getValid() << "</valid>";
		os << indent << "<xMaxLimit>" << getXMaxLimit() << "</xMaxLimit>";
		os << indent << "<xMinLimit>" << getXMinLimit() << "</xMinLimit>";
		os << indent << "<yMaxLimit>" << getYMaxLimit() << "</yMaxLimit>";
		os << indent << "<yMinLimit>" << getYMinLimit() << "</yMinLimit>";
		os << indent << "<zMaxLimit>" << getZMaxLimit() << "</zMaxLimit>";
		os << indent << "<zMinLimit>" << getZMinLimit() << "</zMinLimit>";
	}
	
	// restore from xml stream
	void CommPredictedDataCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_valid("<valid>");
		static const Smart::KnuthMorrisPratt kmp_xMaxLimit("<xMaxLimit>");
		static const Smart::KnuthMorrisPratt kmp_xMinLimit("<xMinLimit>");
		static const Smart::KnuthMorrisPratt kmp_yMaxLimit("<yMaxLimit>");
		static const Smart::KnuthMorrisPratt kmp_yMinLimit("<yMinLimit>");
		static const Smart::KnuthMorrisPratt kmp_zMaxLimit("<zMaxLimit>");
		static const Smart::KnuthMorrisPratt kmp_zMinLimit("<zMinLimit>");
		
		if(kmp_valid.search(is)) {
			bool validItem;
			is >> validItem;
			setValid(validItem);
		}
		if(kmp_xMaxLimit.search(is)) {
			double xMaxLimitItem;
			is >> xMaxLimitItem;
			setXMaxLimit(xMaxLimitItem);
		}
		if(kmp_xMinLimit.search(is)) {
			double xMinLimitItem;
			is >> xMinLimitItem;
			setXMinLimit(xMinLimitItem);
		}
		if(kmp_yMaxLimit.search(is)) {
			double yMaxLimitItem;
			is >> yMaxLimitItem;
			setYMaxLimit(yMaxLimitItem);
		}
		if(kmp_yMinLimit.search(is)) {
			double yMinLimitItem;
			is >> yMinLimitItem;
			setYMinLimit(yMinLimitItem);
		}
		if(kmp_zMaxLimit.search(is)) {
			double zMaxLimitItem;
			is >> zMaxLimitItem;
			setZMaxLimit(zMaxLimitItem);
		}
		if(kmp_zMinLimit.search(is)) {
			double zMinLimitItem;
			is >> zMinLimitItem;
			setZMinLimit(zMinLimitItem);
		}
	}
	
	/*
	void CommPredictedDataCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainHumanTrackingIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainHumanTrackingIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommPredictedDataACE.hh)
		cdr << idl_CommPredictedData;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommPredictedData);
		cdr << data_hash;
		// std::cout << "CommPredictedDataCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommPredictedDataCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainHumanTrackingIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommPredictedDataACE.hh)
		cdr >> idl_CommPredictedData;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommPredictedData);
		assert(data_hash == own_hash);
		// std::cout << "CommPredictedDataCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainHumanTracking */
