//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_ACE_H_
#define DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_ACE_H_

#include "DomainHumanTracking/CommHumanPositionPredictions.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommHumanPositionPredictions
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTrackingIDL::CommHumanPositionPredictions &data);

// de-serialization operator for DataStructure CommHumanPositionPredictions
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTrackingIDL::CommHumanPositionPredictions &data);

// serialization operator for CommunicationObject CommHumanPositionPredictions
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainHumanTracking::CommHumanPositionPredictions &obj);

// de-serialization operator for CommunicationObject CommHumanPositionPredictions
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainHumanTracking::CommHumanPositionPredictions &obj);

#endif /* DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_ACE_H_ */
