//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONSREQUEST_CORE_H_
#define DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONSREQUEST_CORE_H_

#include "DomainHumanTracking/CommHumanPositionPredictionsRequestData.hh"
#include "CommBasicObjects/CommTimeStamp.hh"
#include "CommBasicObjects/CommPose3d.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainHumanTracking {
	
class CommHumanPositionPredictionsRequestCore {
protected:
	// data structure
	DomainHumanTrackingIDL::CommHumanPositionPredictionsRequest idl_CommHumanPositionPredictionsRequest;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainHumanTrackingIDL::CommHumanPositionPredictionsRequest DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommHumanPositionPredictionsRequestCore();
	CommHumanPositionPredictionsRequestCore(const DATATYPE &data);
	// default destructor
	virtual ~CommHumanPositionPredictionsRequestCore();
	
	const DATATYPE& get() const { return idl_CommHumanPositionPredictionsRequest; }
	operator const DATATYPE&() const { return idl_CommHumanPositionPredictionsRequest; }
	DATATYPE& set() { return idl_CommHumanPositionPredictionsRequest; }

	static inline std::string identifier(void) { return "DomainHumanTracking::CommHumanPositionPredictionsRequest"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element TimeFrame
	inline CommBasicObjects::CommTimeStamp getTimeFrame() const { return CommBasicObjects::CommTimeStamp(idl_CommHumanPositionPredictionsRequest.timeFrame); }
	inline CommHumanPositionPredictionsRequestCore& setTimeFrame(const CommBasicObjects::CommTimeStamp &timeFrame) { idl_CommHumanPositionPredictionsRequest.timeFrame = timeFrame; return *this; }
	
	// getter and setter for element FrameOfReference
	inline CommBasicObjects::CommPose3d getFrameOfReference() const { return CommBasicObjects::CommPose3d(idl_CommHumanPositionPredictionsRequest.frameOfReference); }
	inline CommHumanPositionPredictionsRequestCore& setFrameOfReference(const CommBasicObjects::CommPose3d &frameOfReference) { idl_CommHumanPositionPredictionsRequest.frameOfReference = frameOfReference; return *this; }
};

} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONSREQUEST_CORE_H_ */
