//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMPREDICTEDDATA_DATA_H_
#define DOMAINHUMANTRACKING_COMMPREDICTEDDATA_DATA_H_



namespace DomainHumanTrackingIDL 
{
	struct CommPredictedData
	{
		bool valid;
		double xMaxLimit;
		double xMinLimit;
		double yMaxLimit;
		double yMinLimit;
		double zMaxLimit;
		double zMinLimit;
  	};
};

#endif /* DOMAINHUMANTRACKING_COMMPREDICTEDDATA_DATA_H_ */
