//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMM2DVECTOR_DATA_H_
#define DOMAINHUMANTRACKING_COMM2DVECTOR_DATA_H_



namespace DomainHumanTrackingIDL 
{
	struct Comm2dVector
	{
		double x;
		double y;
  	};
};

#endif /* DOMAINHUMANTRACKING_COMM2DVECTOR_DATA_H_ */
