//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_DATA_H_
#define DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_DATA_H_

#include "DomainHumanTracking/CommPredictedDataData.hh"

#include <vector>

namespace DomainHumanTrackingIDL 
{
	typedef std::vector<DomainHumanTrackingIDL::CommPredictedData> CommHumanPositionPredictions_predictedData_type;
	struct CommHumanPositionPredictions
	{
		CommHumanPositionPredictions_predictedData_type predictedData;
  	};
};

#endif /* DOMAINHUMANTRACKING_COMMHUMANPOSITIONPREDICTIONS_DATA_H_ */
