//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMM3DVECTOR_CORE_H_
#define DOMAINHUMANTRACKING_COMM3DVECTOR_CORE_H_

#include "DomainHumanTracking/Comm3dVectorData.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainHumanTracking {
	
class Comm3dVectorCore {
protected:
	// data structure
	DomainHumanTrackingIDL::Comm3dVector idl_Comm3dVector;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainHumanTrackingIDL::Comm3dVector DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	Comm3dVectorCore();
	Comm3dVectorCore(const DATATYPE &data);
	// default destructor
	virtual ~Comm3dVectorCore();
	
	const DATATYPE& get() const { return idl_Comm3dVector; }
	operator const DATATYPE&() const { return idl_Comm3dVector; }
	DATATYPE& set() { return idl_Comm3dVector; }

	static inline std::string identifier(void) { return "DomainHumanTracking::Comm3dVector"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element X
	inline double getX() const { return idl_Comm3dVector.x; }
	inline Comm3dVectorCore& setX(const double &x) { idl_Comm3dVector.x = x; return *this; }
	
	// getter and setter for element Y
	inline double getY() const { return idl_Comm3dVector.y; }
	inline Comm3dVectorCore& setY(const double &y) { idl_Comm3dVector.y = y; return *this; }
	
	// getter and setter for element Z
	inline double getZ() const { return idl_Comm3dVector.z; }
	inline Comm3dVectorCore& setZ(const double &z) { idl_Comm3dVector.z = z; return *this; }
};

} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMM3DVECTOR_CORE_H_ */
