//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMM2DVECTOR_CORE_H_
#define DOMAINHUMANTRACKING_COMM2DVECTOR_CORE_H_

#include "DomainHumanTracking/Comm2dVectorData.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainHumanTracking {
	
class Comm2dVectorCore {
protected:
	// data structure
	DomainHumanTrackingIDL::Comm2dVector idl_Comm2dVector;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainHumanTrackingIDL::Comm2dVector DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	Comm2dVectorCore();
	Comm2dVectorCore(const DATATYPE &data);
	// default destructor
	virtual ~Comm2dVectorCore();
	
	const DATATYPE& get() const { return idl_Comm2dVector; }
	operator const DATATYPE&() const { return idl_Comm2dVector; }
	DATATYPE& set() { return idl_Comm2dVector; }

	static inline std::string identifier(void) { return "DomainHumanTracking::Comm2dVector"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element X
	inline double getX() const { return idl_Comm2dVector.x; }
	inline Comm2dVectorCore& setX(const double &x) { idl_Comm2dVector.x = x; return *this; }
	
	// getter and setter for element Y
	inline double getY() const { return idl_Comm2dVector.y; }
	inline Comm2dVectorCore& setY(const double &y) { idl_Comm2dVector.y = y; return *this; }
};

} /* namespace DomainHumanTracking */
#endif /* DOMAINHUMANTRACKING_COMM2DVECTOR_CORE_H_ */
