//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMBODYDATA_DATA_H_
#define DOMAINHUMANTRACKING_COMMBODYDATA_DATA_H_

#include "DomainHumanTracking/enumHandTrackingStateTypeData.hh"
#include "DomainHumanTracking/CommJointDataData.hh"
#include "CommBasicObjects/CommTimeStampData.hh"

#include <vector>

namespace DomainHumanTrackingIDL 
{
	typedef std::vector<DomainHumanTrackingIDL::CommJointData> CommBodyData_jointData_type;
	struct CommBodyData
	{
		bool isTracked;
		CommBasicObjectsIDL::CommTimeStamp acquisitionTime;
		DomainHumanTrackingIDL::HandTrackingStateType leftHandState;
		DomainHumanTrackingIDL::HandTrackingStateType rightHandState;
		CommBodyData_jointData_type jointData;
  	};
};

#endif /* DOMAINHUMANTRACKING_COMMBODYDATA_DATA_H_ */
