//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_COMMJOINTDATA_DATA_H_
#define DOMAINHUMANTRACKING_COMMJOINTDATA_DATA_H_

#include "DomainHumanTracking/Comm2dVectorData.hh"
#include "DomainHumanTracking/Comm3dVectorData.hh"
#include "DomainHumanTracking/enumJointTrackingStateTypeData.hh"


namespace DomainHumanTrackingIDL 
{
	struct CommJointData
	{
		DomainHumanTrackingIDL::JointTrackingStateType isJointTracked;
		DomainHumanTrackingIDL::Comm2dVector jointPosition2D;
		DomainHumanTrackingIDL::Comm2dVector jointVelocity2D;
		DomainHumanTrackingIDL::Comm3dVector jointPosition3d;
		DomainHumanTrackingIDL::Comm3dVector jointVelocity3d;
  	};
};

#endif /* DOMAINHUMANTRACKING_COMMJOINTDATA_DATA_H_ */
