//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainHumanTracking/CommHumanPositionPredictionsCore.hh"

// serialization/deserialization operators
//#include "DomainHumanTracking/CommHumanPositionPredictionsACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainHumanTracking 
{
	const char* CommHumanPositionPredictionsCore::getCompiledHash()
	{
		return DomainHumanTrackingIDL::REPO_HASH;
	}
	
	void CommHumanPositionPredictionsCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for DomainHumanTracking::CommPredictedData(idl_CommHumanPositionPredictions.predictedData)
		DomainHumanTracking::CommPredictedData::getAllHashValues(hashes);
	}
	
	void CommHumanPositionPredictionsCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommHumanPositionPredictionsCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for DomainHumanTracking::CommPredictedData(idl_CommHumanPositionPredictions.predictedData)
		DomainHumanTracking::CommPredictedData::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommHumanPositionPredictionsCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<DomainHumanTrackingIDL::CommPredictedData>::const_iterator data_predictedDataIt;
		for(data_predictedDataIt=data.predictedData.begin(); data_predictedDataIt!=data.predictedData.end(); data_predictedDataIt++) {
			seed += DomainHumanTracking::CommPredictedData::generateDataHash(*data_predictedDataIt);
		}
		
		return seed;
	}
	#endif
	
	// default constructor
	CommHumanPositionPredictionsCore::CommHumanPositionPredictionsCore()
	:	idl_CommHumanPositionPredictions()
	{  
		setPredictedData(std::vector<DomainHumanTracking::CommPredictedData>());
	}
	
	CommHumanPositionPredictionsCore::CommHumanPositionPredictionsCore(const DATATYPE &data)
	:	idl_CommHumanPositionPredictions(data)
	{  }

	CommHumanPositionPredictionsCore::~CommHumanPositionPredictionsCore()
	{  }
	
	void CommHumanPositionPredictionsCore::to_ostream(std::ostream &os) const
	{
	  os << "CommHumanPositionPredictions(";
	  std::vector<DomainHumanTracking::CommPredictedData>::const_iterator predictedDataIt;
	  std::vector<DomainHumanTracking::CommPredictedData> predictedDataList = getPredictedDataCopy();
	  for(predictedDataIt=predictedDataList.begin(); predictedDataIt!=predictedDataList.end(); predictedDataIt++) {
	  	predictedDataIt->to_ostream(os);
	  }
	  os << ") ";
	}
	
	// convert to xml stream
	void CommHumanPositionPredictionsCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<DomainHumanTracking::CommPredictedData>::const_iterator predictedDataIt;
		std::vector<DomainHumanTracking::CommPredictedData> predictedDataList = getPredictedDataCopy();
		counter = 0;
		os << indent << "<predictedDataList n=\"" << predictedDataList.size() << "\">";
		for(predictedDataIt=predictedDataList.begin(); predictedDataIt!=predictedDataList.end(); predictedDataIt++) {
			os << indent << "<predictedData i=\"" << counter++ << "\">";
			predictedDataIt->to_xml(os, indent);
			os << indent << "</predictedData>";
		}
		os << indent << "</predictedDataList>";
	}
	
	// restore from xml stream
	void CommHumanPositionPredictionsCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_predictedDataList("<predictedDataList n=\"");
		static const Smart::KnuthMorrisPratt kmp_predictedData("\">");
		
		if(kmp_predictedDataList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			DomainHumanTracking::CommPredictedData predictedDataItem;
			std::vector<DomainHumanTracking::CommPredictedData> predictedDataList;
			kmp_predictedData.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_predictedData.search(is)) {
					predictedDataItem.from_xml(is);
					predictedDataList.push_back(predictedDataItem);
				}
			}
			setPredictedData(predictedDataList);
		}
	}
	
	/*
	void CommHumanPositionPredictionsCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainHumanTrackingIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainHumanTrackingIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommHumanPositionPredictionsACE.hh)
		cdr << idl_CommHumanPositionPredictions;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommHumanPositionPredictions);
		cdr << data_hash;
		// std::cout << "CommHumanPositionPredictionsCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommHumanPositionPredictionsCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainHumanTrackingIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommHumanPositionPredictionsACE.hh)
		cdr >> idl_CommHumanPositionPredictions;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommHumanPositionPredictions);
		assert(data_hash == own_hash);
		// std::cout << "CommHumanPositionPredictionsCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainHumanTracking */
