//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_HANDTRACKINGSTATETYPE_ENUM_H_
#define DOMAINHUMANTRACKING_HANDTRACKINGSTATETYPE_ENUM_H_

#include <DomainHumanTracking/enumHandTrackingStateTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainHumanTracking {
	
	class HandTrackingStateType {
	private:
		DomainHumanTrackingIDL::HandTrackingStateType value;
		
	public:
		enum ENUM_HandTrackingStateType {
			ENUM_VALUE_UNDEFINED = 0,
			OPEN = 1,
			CLOSED = 2,
			NEUTRAL = 3,
			UNKNOWN = 4
		};
		
		// default constructor
		HandTrackingStateType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		HandTrackingStateType(ENUM_HandTrackingStateType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		HandTrackingStateType(DomainHumanTrackingIDL::HandTrackingStateType e) {
			value = e;
		}
		
		//const DomainHumanTrackingIDL::HandTrackingStateType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_HandTrackingStateType() const {
			return static_cast<ENUM_HandTrackingStateType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_HandTrackingStateType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case OPEN:
					result = "HandTrackingStateType::OPEN";
					break;
				case CLOSED:
					result = "HandTrackingStateType::CLOSED";
					break;
				case NEUTRAL:
					result = "HandTrackingStateType::NEUTRAL";
					break;
				case UNKNOWN:
					result = "HandTrackingStateType::UNKNOWN";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const HandTrackingStateType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
