//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINHUMANTRACKING_JOINTTRACKINGSTATETYPE_ENUM_H_
#define DOMAINHUMANTRACKING_JOINTTRACKINGSTATETYPE_ENUM_H_

#include <DomainHumanTracking/enumJointTrackingStateTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainHumanTracking {
	
	class JointTrackingStateType {
	private:
		DomainHumanTrackingIDL::JointTrackingStateType value;
		
	public:
		enum ENUM_JointTrackingStateType {
			ENUM_VALUE_UNDEFINED = 0,
			TRACKED = 1,
			INFERRED = 2,
			UNKNOWN = 3
		};
		
		// default constructor
		JointTrackingStateType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		JointTrackingStateType(ENUM_JointTrackingStateType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		JointTrackingStateType(DomainHumanTrackingIDL::JointTrackingStateType e) {
			value = e;
		}
		
		//const DomainHumanTrackingIDL::JointTrackingStateType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_JointTrackingStateType() const {
			return static_cast<ENUM_JointTrackingStateType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_JointTrackingStateType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case TRACKED:
					result = "JointTrackingStateType::TRACKED";
					break;
				case INFERRED:
					result = "JointTrackingStateType::INFERRED";
					break;
				case UNKNOWN:
					result = "JointTrackingStateType::UNKNOWN";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const JointTrackingStateType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
