//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentSimpleHumanBehaviourPredictor.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentSimpleHumanBehaviourPredictorAcePortFactory.hh"


// initialize static singleton pointer to zero
ComponentSimpleHumanBehaviourPredictor* ComponentSimpleHumanBehaviourPredictor::_componentSimpleHumanBehaviourPredictor = 0;

// constructor
ComponentSimpleHumanBehaviourPredictor::ComponentSimpleHumanBehaviourPredictor()
{
	std::cout << "constructor of ComponentSimpleHumanBehaviourPredictor\n";
	
	// set all pointer members to NULL
	//componentSimpleHumanBehaviourPredictorParams = NULL;
	//coordinationPort = NULL;
	humanPredictionsPushServiceOut = NULL;
	humanPredictionsRequestAnsw = NULL;
	humanPredictionsRequestAnswInputTaskTrigger = NULL;
	humanPredictionsRequestAnswHandler = NULL;
	humanSkeletonsPushServiceIn = NULL;
	humanSkeletonsPushServiceInInputTaskTrigger = NULL;
	humanSkeletonsPushServiceInUpcallManager = NULL;
	simpleHumanPredictionActivity = NULL;
	simpleHumanPredictionActivityTrigger = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	param = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentSimpleHumanBehaviourPredictor";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.humanPredictionsPushServiceOut.serviceName = "HumanPredictionsPushServiceOut";
	connections.humanPredictionsPushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.humanPredictionsRequestAnsw.serviceName = "HumanPredictionsRequestAnsw";
	connections.humanPredictionsRequestAnsw.roboticMiddleware = "ACE_SmartSoft";
	connections.humanSkeletonsPushServiceIn.wiringName = "HumanSkeletonsPushServiceIn";
	connections.humanSkeletonsPushServiceIn.serverName = "unknown";
	connections.humanSkeletonsPushServiceIn.serviceName = "unknown";
	connections.humanSkeletonsPushServiceIn.interval = 1;
	connections.humanSkeletonsPushServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.simpleHumanPredictionActivity.minActFreq = 0.0;
	connections.simpleHumanPredictionActivity.maxActFreq = 0.0;
	connections.simpleHumanPredictionActivity.trigger = "PeriodicTimer";
	connections.simpleHumanPredictionActivity.periodicActFreq = 30.0;
	// scheduling default parameters
	connections.simpleHumanPredictionActivity.scheduler = "DEFAULT";
	connections.simpleHumanPredictionActivity.priority = -1;
	connections.simpleHumanPredictionActivity.cpuAffinity = -1;
	
	// initialize members of ComponentSimpleHumanBehaviourPredictorROSExtension
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaComponentSimpleHumanBehaviourPredictorExtension
	
}

void ComponentSimpleHumanBehaviourPredictor::addPortFactory(const std::string &name, ComponentSimpleHumanBehaviourPredictorPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentSimpleHumanBehaviourPredictor::addExtension(ComponentSimpleHumanBehaviourPredictorExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentSimpleHumanBehaviourPredictor::getComponentImpl()
{
	return dynamic_cast<ComponentSimpleHumanBehaviourPredictorAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentSimpleHumanBehaviourPredictor::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode ComponentSimpleHumanBehaviourPredictor::connectHumanSkeletonsPushServiceIn(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = humanSkeletonsPushServiceIn->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->humanSkeletonsPushServiceIn->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	humanSkeletonsPushServiceIn->subscribe(connections.humanSkeletonsPushServiceIn.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentSimpleHumanBehaviourPredictor::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectHumanSkeletonsPushServiceIn(connections.humanSkeletonsPushServiceIn.serverName, connections.humanSkeletonsPushServiceIn.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentSimpleHumanBehaviourPredictor::startAllTasks() {
	// start task SimpleHumanPredictionActivity
	if(connections.simpleHumanPredictionActivity.scheduler != "DEFAULT") {
		ACE_Sched_Params simpleHumanPredictionActivity_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.simpleHumanPredictionActivity.scheduler == "FIFO") {
			simpleHumanPredictionActivity_SchedParams.policy(ACE_SCHED_FIFO);
			simpleHumanPredictionActivity_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.simpleHumanPredictionActivity.scheduler == "RR") {
			simpleHumanPredictionActivity_SchedParams.policy(ACE_SCHED_RR);
			simpleHumanPredictionActivity_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		simpleHumanPredictionActivity->start(simpleHumanPredictionActivity_SchedParams, connections.simpleHumanPredictionActivity.cpuAffinity);
	} else {
		simpleHumanPredictionActivity->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentSimpleHumanBehaviourPredictor::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentSimpleHumanBehaviourPredictor::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "HumanSkeletonsPushServiceIn") return humanSkeletonsPushServiceInInputTaskTrigger;
	
	return NULL;
}


void ComponentSimpleHumanBehaviourPredictor::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		// print out the actual parameters which are used to initialize the component
		std::cout << " \nComponentDefinition Initial-Parameters:\n" << COMP->getParameters() << std::endl;
		
		// initializations of ComponentSimpleHumanBehaviourPredictorROSExtension
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaComponentSimpleHumanBehaviourPredictorExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentSimpleHumanBehaviourPredictorPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentSimpleHumanBehaviourPredictorAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentSimpleHumanBehaviourPredictor is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		humanPredictionsPushServiceOut = portFactoryRegistry[connections.humanPredictionsPushServiceOut.roboticMiddleware]->createHumanPredictionsPushServiceOut(connections.humanPredictionsPushServiceOut.serviceName);
		humanPredictionsRequestAnsw = portFactoryRegistry[connections.humanPredictionsRequestAnsw.roboticMiddleware]->createHumanPredictionsRequestAnsw(connections.humanPredictionsRequestAnsw.serviceName);
		humanPredictionsRequestAnswInputTaskTrigger = new Smart::QueryServerTaskTrigger<DomainHumanTracking::CommHumanPositionPredictionsRequest, DomainHumanTracking::CommHumanPositionPredictions>(humanPredictionsRequestAnsw);
		
		// create client ports
		humanSkeletonsPushServiceIn = portFactoryRegistry[connections.humanSkeletonsPushServiceIn.roboticMiddleware]->createHumanSkeletonsPushServiceIn();
		
		// create InputTaskTriggers and UpcallManagers
		humanSkeletonsPushServiceInInputTaskTrigger = new Smart::InputTaskTrigger<DomainHumanTracking::CommHumanPositionsAndVelocities>(humanSkeletonsPushServiceIn);
		humanSkeletonsPushServiceInUpcallManager = new HumanSkeletonsPushServiceInUpcallManager(humanSkeletonsPushServiceIn);
		
		// create input-handler
		
		// create request-handlers
		humanPredictionsRequestAnswHandler = new HumanPredictionsRequestAnswHandler(humanPredictionsRequestAnsw);
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.humanSkeletonsPushServiceIn.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainHumanTracking::CommHumanPositionsAndVelocities>*>(humanSkeletonsPushServiceIn)->add(wiringSlave, connections.humanSkeletonsPushServiceIn.wiringName);
		}
		
		// create parameter slave
		param = new SmartACE::ParameterSlave(component, &paramHandler);
		
		
		// create Task SimpleHumanPredictionActivity
		simpleHumanPredictionActivity = new SimpleHumanPredictionActivity(component);
		// configure input-links
		humanSkeletonsPushServiceInUpcallManager->attach(simpleHumanPredictionActivity);
		// configure task-trigger (if task is configurable)
		if(connections.simpleHumanPredictionActivity.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.simpleHumanPredictionActivity.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(simpleHumanPredictionActivity);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				simpleHumanPredictionActivityTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task SimpleHumanPredictionActivity" << std::endl;
			}
		} else if(connections.simpleHumanPredictionActivity.trigger == "DataTriggered") {
			simpleHumanPredictionActivityTrigger = getInputTaskTriggerFromString(connections.simpleHumanPredictionActivity.inPortRef);
			if(simpleHumanPredictionActivityTrigger != NULL) {
				simpleHumanPredictionActivityTrigger->attach(simpleHumanPredictionActivity, connections.simpleHumanPredictionActivity.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.simpleHumanPredictionActivity.inPortRef << " as activation source for Task SimpleHumanPredictionActivity" << std::endl;
			}
		} else
		{
			// setup default task-trigger as PeriodicTimer
			Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
			int microseconds = 1000*1000 / 30.0;
			if(microseconds > 0) {
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				triggerPtr->attach(simpleHumanPredictionActivity);
				// store trigger in class member
				simpleHumanPredictionActivityTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task SimpleHumanPredictionActivity" << std::endl;
			}
		}
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentSimpleHumanBehaviourPredictor::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentSimpleHumanBehaviourPredictor::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	humanSkeletonsPushServiceInUpcallManager->detach(simpleHumanPredictionActivity);
	// unlink the TaskTrigger
	if(simpleHumanPredictionActivityTrigger != NULL){
		simpleHumanPredictionActivityTrigger->detach(simpleHumanPredictionActivity);
		delete simpleHumanPredictionActivity;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete humanSkeletonsPushServiceInInputTaskTrigger;
	delete humanSkeletonsPushServiceInUpcallManager;

	// destroy client ports
	delete humanSkeletonsPushServiceIn;

	// destroy server ports
	delete humanPredictionsPushServiceOut;
	delete humanPredictionsRequestAnsw;
	delete humanPredictionsRequestAnswInputTaskTrigger;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	delete humanPredictionsRequestAnswHandler;
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	delete param;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of ComponentSimpleHumanBehaviourPredictorROSExtension
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaComponentSimpleHumanBehaviourPredictorExtension
	
}

void ComponentSimpleHumanBehaviourPredictor::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentSimpleHumanBehaviourPredictor.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentSimpleHumanBehaviourPredictor.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentSimpleHumanBehaviourPredictor.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client HumanSkeletonsPushServiceIn
		parameter.getString("HumanSkeletonsPushServiceIn", "serviceName", connections.humanSkeletonsPushServiceIn.serviceName);
		parameter.getString("HumanSkeletonsPushServiceIn", "serverName", connections.humanSkeletonsPushServiceIn.serverName);
		parameter.getString("HumanSkeletonsPushServiceIn", "wiringName", connections.humanSkeletonsPushServiceIn.wiringName);
		parameter.getInteger("HumanSkeletonsPushServiceIn", "interval", connections.humanSkeletonsPushServiceIn.interval);
		if(parameter.checkIfParameterExists("HumanSkeletonsPushServiceIn", "roboticMiddleware")) {
			parameter.getString("HumanSkeletonsPushServiceIn", "roboticMiddleware", connections.humanSkeletonsPushServiceIn.roboticMiddleware);
		}
		
		// load parameters for server HumanPredictionsPushServiceOut
		parameter.getString("HumanPredictionsPushServiceOut", "serviceName", connections.humanPredictionsPushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("HumanPredictionsPushServiceOut", "roboticMiddleware")) {
			parameter.getString("HumanPredictionsPushServiceOut", "roboticMiddleware", connections.humanPredictionsPushServiceOut.roboticMiddleware);
		}
		// load parameters for server HumanPredictionsRequestAnsw
		parameter.getString("HumanPredictionsRequestAnsw", "serviceName", connections.humanPredictionsRequestAnsw.serviceName);
		if(parameter.checkIfParameterExists("HumanPredictionsRequestAnsw", "roboticMiddleware")) {
			parameter.getString("HumanPredictionsRequestAnsw", "roboticMiddleware", connections.humanPredictionsRequestAnsw.roboticMiddleware);
		}
		
		// load parameters for task SimpleHumanPredictionActivity
		parameter.getDouble("SimpleHumanPredictionActivity", "minActFreqHz", connections.simpleHumanPredictionActivity.minActFreq);
		parameter.getDouble("SimpleHumanPredictionActivity", "maxActFreqHz", connections.simpleHumanPredictionActivity.maxActFreq);
		parameter.getString("SimpleHumanPredictionActivity", "triggerType", connections.simpleHumanPredictionActivity.trigger);
		if(connections.simpleHumanPredictionActivity.trigger == "PeriodicTimer") {
			parameter.getDouble("SimpleHumanPredictionActivity", "periodicActFreqHz", connections.simpleHumanPredictionActivity.periodicActFreq);
		} else if(connections.simpleHumanPredictionActivity.trigger == "DataTriggered") {
			parameter.getString("SimpleHumanPredictionActivity", "inPortRef", connections.simpleHumanPredictionActivity.inPortRef);
			parameter.getInteger("SimpleHumanPredictionActivity", "prescale", connections.simpleHumanPredictionActivity.prescale);
		}
		if(parameter.checkIfParameterExists("SimpleHumanPredictionActivity", "scheduler")) {
			parameter.getString("SimpleHumanPredictionActivity", "scheduler", connections.simpleHumanPredictionActivity.scheduler);
		}
		if(parameter.checkIfParameterExists("SimpleHumanPredictionActivity", "priority")) {
			parameter.getInteger("SimpleHumanPredictionActivity", "priority", connections.simpleHumanPredictionActivity.priority);
		}
		if(parameter.checkIfParameterExists("SimpleHumanPredictionActivity", "cpuAffinity")) {
			parameter.getInteger("SimpleHumanPredictionActivity", "cpuAffinity", connections.simpleHumanPredictionActivity.cpuAffinity);
		}
		
		// load parameters for ComponentSimpleHumanBehaviourPredictorROSExtension
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaComponentSimpleHumanBehaviourPredictorExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
		paramHandler.loadParameter(parameter);
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
