//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SIMPLEHUMANPREDICTIONACTIVITY_CORE_HH
#define _SIMPLEHUMANPREDICTIONACTIVITY_CORE_HH
	
#include "aceSmartSoft.hh"

// include upcall interface
#include "HumanSkeletonsPushServiceInUpcallInterface.hh"

// include communication-objects for output ports
#include <DomainHumanTracking/CommHumanPositionPredictions.hh>

// include all interaction-observer interfaces
#include <SimpleHumanPredictionActivityObserverInterface.hh>


class SimpleHumanPredictionActivityCore
:	public SmartACE::ManagedTask
,	public Smart::TaskTriggerSubject
,	public HumanSkeletonsPushServiceInUpcallInterface
{
private:
	bool useDefaultState; 
	bool useLogging;
	int taskLoggingId;
	unsigned int currentUpdateCount;
	
	Smart::StatusCode humanSkeletonsPushServiceInStatus;
	DomainHumanTracking::CommHumanPositionsAndVelocities humanSkeletonsPushServiceInObject;
	
	
protected:
	virtual int execute_protected_region();
	
	virtual void updateAllCommObjects();
	
	virtual int getPreviousCommObjId();
	
	void triggerLogEntry(const int& idOffset);
	
	
	// overload and implement this method in derived classes to immediately get all incoming updates from HumanSkeletonsPushServiceIn (as soon as they arrive)
	virtual void on_HumanSkeletonsPushServiceIn(const DomainHumanTracking::CommHumanPositionsAndVelocities &input) {
		// no-op
	}
	
	// this method can be safely used from the thread in derived classes
	inline Smart::StatusCode humanSkeletonsPushServiceInGetUpdate(DomainHumanTracking::CommHumanPositionsAndVelocities &humanSkeletonsPushServiceInObject) const
	{
		// copy local object buffer and return the last status code
		humanSkeletonsPushServiceInObject = this->humanSkeletonsPushServiceInObject;
		return humanSkeletonsPushServiceInStatus;
	}
	
	// this method is meant to be used in derived classes
	Smart::StatusCode humanPredictionsPushServiceOutPut(DomainHumanTracking::CommHumanPositionPredictions &humanPredictionsPushServiceOutDataObject);
	
	
/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<SimpleHumanPredictionActivityObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(SimpleHumanPredictionActivityObserverInterface *observer);
	void detach_interaction_observer(SimpleHumanPredictionActivityObserverInterface *observer);

public:
	SimpleHumanPredictionActivityCore(Smart::IComponent *comp, const bool &useDefaultState=true);
	virtual ~SimpleHumanPredictionActivityCore();
	
	inline void setUpLogging(const int &taskNbr, const bool &useLogging=true) {
		this->taskLoggingId = taskNbr;
		this->useLogging = useLogging;
	}
	
	inline bool isLoggingActive() const {
		return useLogging;
	}
	
	inline int getLoggingID() const {
		return taskLoggingId;
	}
	
	inline int getCurrentUpdateCount() const {
		return currentUpdateCount;
	}
	
};
#endif
